goog.addDependency('../../../js-src/ajaxactions.js', ['plt.wescheme.AjaxActions'], ['plt.wescheme.Program']);
goog.addDependency('../../../js-src/base64.js', ['plt.wescheme.base64'], []);
goog.addDependency('../../../js-src/browser-check.js', ['plt.wescheme.browserCheck'], ['plt.wescheme.BrowserDetect', 'plt.wescheme.cookies']);
goog.addDependency('../../../js-src/browser-detect.js', ['plt.wescheme.BrowserDetect'], []);
goog.addDependency('../../../js-src/compiler/analyzer.js', ['plt.compiler.analyze', 'plt.compiler.desugar'], ['plt.compiler.Program', 'plt.compiler.andExpr', 'plt.compiler.beginExpr', 'plt.compiler.callExpr', 'plt.compiler.caseExpr', 'plt.compiler.condExpr', 'plt.compiler.constantBinding', 'plt.compiler.couple', 'plt.compiler.defFunc', 'plt.compiler.defStruct', 'plt.compiler.defVar', 'plt.compiler.defVars', 'plt.compiler.functionBinding', 'plt.compiler.ifExpr', 'plt.compiler.knownModules', 'plt.compiler.lambdaExpr', 'plt.compiler.letExpr', 'plt.compiler.letStarExpr', 'plt.compiler.letrecExpr', 'plt.compiler.literal', 'plt.compiler.localExpr', 'plt.compiler.moduleBinding', 'plt.compiler.orExpr', 'plt.compiler.provideStatement', 'plt.compiler.quasiquotedExpr', 'plt.compiler.quotedExpr', 'plt.compiler.requireExpr', 'plt.compiler.structBinding', 'plt.compiler.symbolExpr', 'plt.compiler.throwError', 'plt.compiler.unquoteSplice', 'plt.compiler.unquotedExpr', 'plt.compiler.unsupportedExpr', 'plt.compiler.whenUnlessExpr']);
goog.addDependency('../../../js-src/compiler/compiler.js', ['plt.compiler.compile', 'plt.compiler.globalStackReference', 'plt.compiler.localStackReference', 'plt.compiler.unboundStackReference'], ['plt.compiler.Program', 'plt.compiler.andExpr', 'plt.compiler.beginExpr', 'plt.compiler.callExpr', 'plt.compiler.defFunc', 'plt.compiler.defStruct', 'plt.compiler.defVar', 'plt.compiler.defVars', 'plt.compiler.ifExpr', 'plt.compiler.lambdaExpr', 'plt.compiler.literal', 'plt.compiler.localExpr', 'plt.compiler.orExpr', 'plt.compiler.provideStatement', 'plt.compiler.quotedExpr', 'plt.compiler.requireExpr', 'plt.compiler.symbolExpr']);
goog.addDependency('../../../js-src/compiler/index.js', [], ['plt.compiler.analyze', 'plt.compiler.compile', 'plt.compiler.desugar', 'plt.compiler.lex', 'plt.compiler.parse']);
goog.addDependency('../../../js-src/compiler/lex.js', ['plt.compiler.lex', 'plt.compiler.sexpToString'], ['plt.compiler.comment', 'plt.compiler.literal', 'plt.compiler.symbolExpr', 'plt.compiler.throwError', 'plt.compiler.unsupportedExpr']);
goog.addDependency('../../../js-src/compiler/modules.js', ['plt.compiler.knownCollections', 'plt.compiler.knownModules', 'plt.compiler.topLevelModules'], ['plt.compiler.constantBinding', 'plt.compiler.functionBinding', 'plt.compiler.moduleBinding']);
goog.addDependency('../../../js-src/compiler/parser.js', ['plt.compiler.parse'], ['plt.compiler.Program', 'plt.compiler.andExpr', 'plt.compiler.beginExpr', 'plt.compiler.callExpr', 'plt.compiler.caseExpr', 'plt.compiler.condExpr', 'plt.compiler.couple', 'plt.compiler.defFunc', 'plt.compiler.defStruct', 'plt.compiler.defVar', 'plt.compiler.defVars', 'plt.compiler.ifExpr', 'plt.compiler.lambdaExpr', 'plt.compiler.letExpr', 'plt.compiler.letStarExpr', 'plt.compiler.letrecExpr', 'plt.compiler.literal', 'plt.compiler.localExpr', 'plt.compiler.orExpr', 'plt.compiler.provideStatement', 'plt.compiler.quasiquotedExpr', 'plt.compiler.quotedExpr', 'plt.compiler.requireExpr', 'plt.compiler.symbolExpr', 'plt.compiler.throwError', 'plt.compiler.unquoteSplice', 'plt.compiler.unquotedExpr', 'plt.compiler.unsupportedExpr', 'plt.compiler.whenUnlessExpr']);
goog.addDependency('../../../js-src/compiler/structures.js', ['plt.compiler.Program', 'plt.compiler.andExpr', 'plt.compiler.beginExpr', 'plt.compiler.callExpr', 'plt.compiler.caseExpr', 'plt.compiler.comment', 'plt.compiler.condExpr', 'plt.compiler.constantBinding', 'plt.compiler.couple', 'plt.compiler.defFunc', 'plt.compiler.defStruct', 'plt.compiler.defVar', 'plt.compiler.defVars', 'plt.compiler.emptyEnv', 'plt.compiler.env', 'plt.compiler.functionBinding', 'plt.compiler.getBasePinfo', 'plt.compiler.globalEnv', 'plt.compiler.ifExpr', 'plt.compiler.isDefinition', 'plt.compiler.isExpression', 'plt.compiler.lambdaExpr', 'plt.compiler.letExpr', 'plt.compiler.letStarExpr', 'plt.compiler.letrecExpr', 'plt.compiler.literal', 'plt.compiler.localEnv', 'plt.compiler.localExpr', 'plt.compiler.moduleBinding', 'plt.compiler.orExpr', 'plt.compiler.pinfo', 'plt.compiler.provideStatement', 'plt.compiler.quasiquotedExpr', 'plt.compiler.quotedExpr', 'plt.compiler.requireExpr', 'plt.compiler.structBinding', 'plt.compiler.symbolExpr', 'plt.compiler.throwError', 'plt.compiler.unnamedEnv', 'plt.compiler.unquoteSplice', 'plt.compiler.unquotedExpr', 'plt.compiler.unsupportedExpr', 'plt.compiler.whenUnlessExpr'], []);
goog.addDependency('../../../js-src/console.js', [], ['plt.wescheme.AjaxActions', 'plt.wescheme.DeleteDialog', 'plt.wescheme.ProgramDigest', 'plt.wescheme.SharingDialog', 'plt.wescheme.browserCheck', 'plt.wescheme.helpers']);
goog.addDependency('../../../js-src/cookies.js', ['plt.wescheme.cookies'], []);
goog.addDependency('../../../js-src/deletedialog.js', ['plt.wescheme.DeleteDialog'], ['goog.ui.AdvancedTooltip', 'plt.wescheme.AjaxActions', 'plt.wescheme.WeSchemeIntentBus', 'plt.wescheme.helpers']);
goog.addDependency('../../../js-src/heartbeat.js', ['plt.wescheme.beat'], []);
goog.addDependency('../../../js-src/helpers.js', ['plt.wescheme.helpers'], []);
goog.addDependency('../../../js-src/intent.js', ['plt.wescheme.WeSchemeIntentBus'], []);
goog.addDependency('../../../js-src/js-runtime/browser-platform.js', [], []);
goog.addDependency('../../../js-src/js-runtime/compat/IE8.js', [], [], {'lang': 'es6'});
goog.addDependency('../../../js-src/js-runtime/compat/XMLHttpRequest.js', [], []);
goog.addDependency('../../../js-src/js-runtime/compat/excanvas.js', [], []);
goog.addDependency('../../../js-src/js-runtime/compat/ie-fixes.js', [], []);
goog.addDependency('../../../js-src/js-runtime/compat/ie7-squish.js', [], []);
goog.addDependency('../../../js-src/js-runtime/control.js', [], []);
goog.addDependency('../../../js-src/js-runtime/exports.js', [], []);
goog.addDependency('../../../js-src/js-runtime/helpers.js', [], []);
goog.addDependency('../../../js-src/js-runtime/index.js', [], []);
goog.addDependency('../../../js-src/js-runtime/interpret.js', [], []);
goog.addDependency('../../../js-src/js-runtime/js-numbers.js', [], []);
goog.addDependency('../../../js-src/js-runtime/jshashtable.js', [], []);
goog.addDependency('../../../js-src/js-runtime/json2.js', [], []);
goog.addDependency('../../../js-src/js-runtime/loader.js', [], []);
goog.addDependency('../../../js-src/js-runtime/md5.js', [], []);
goog.addDependency('../../../js-src/js-runtime/node-platform.js', [], []);
goog.addDependency('../../../js-src/js-runtime/primitive.js', [], []);
goog.addDependency('../../../js-src/js-runtime/state.js', [], []);
goog.addDependency('../../../js-src/js-runtime/types.js', [], []);
goog.addDependency('../../../js-src/js-runtime/world/jsworld.js', [], []);
goog.addDependency('../../../js-src/js-runtime/world/jsworld/jsworld.js', [], []);
goog.addDependency('../../../js-src/js-runtime/world/world-config.js', [], []);
goog.addDependency('../../../js-src/js-runtime/world/world-stimuli.js', [], []);
goog.addDependency('../../../js-src/js-runtime/world/world.js', [], []);
goog.addDependency('../../../js-src/notesdialog.js', ['plt.wescheme.NotesDialog'], ['goog.ui.AdvancedTooltip', 'plt.wescheme.AjaxActions', 'plt.wescheme.WeSchemeIntentBus', 'plt.wescheme.helpers']);
goog.addDependency('../../../js-src/openEditor/config.js', ['plt.config'], []);
goog.addDependency('../../../js-src/openEditor/dynamic-module-loader.js', ['plt.wescheme.makeDynamicModuleLoader'], ['plt.wescheme.AjaxActions']);
goog.addDependency('../../../js-src/openEditor/editor.js', ['plt.wescheme.WeSchemeEditor'], ['plt.config', 'plt.wescheme.AjaxActions', 'plt.wescheme.NotesDialog', 'plt.wescheme.SharingDialog', 'plt.wescheme.WeSchemeIntentBus', 'plt.wescheme.WeSchemeInteractions', 'plt.wescheme.helpers', 'plt.wescheme.tokenizer']);
goog.addDependency('../../../js-src/openEditor/index.js', [], ['goog.dom.ViewportSizeMonitor', 'goog.math.Size', 'goog.style', 'goog.ui.Container', 'goog.ui.SplitPane', 'goog.ui.SplitPane.Orientation', 'plt.wescheme.WeSchemeEditor', 'plt.wescheme.WeSchemeStatusBar', 'plt.wescheme.WeSchemeTextContainer', 'plt.wescheme.browserCheck', 'plt.wescheme.selenium', 'plt.wescheme.topKeymap']);
goog.addDependency('../../../js-src/openEditor/interaction.js', ['plt.wescheme.WeSchemeInteractions'], ['plt.wescheme.RoundRobin', 'plt.wescheme.WeSchemeProperties', 'plt.wescheme.WeSchemeTextContainer', 'plt.wescheme.makeDynamicModuleLoader', 'plt.wescheme.tokenizer', 'plt.wescheme.topKeymap']);
goog.addDependency('../../../js-src/openEditor/round_robin.js', ['plt.wescheme.RoundRobin'], ['plt.compiler.analyze', 'plt.compiler.compile', 'plt.compiler.desugar', 'plt.compiler.lex', 'plt.compiler.parse']);
goog.addDependency('../../../js-src/openEditor/selenium.js', ['plt.wescheme.selenium'], []);
goog.addDependency('../../../js-src/openEditor/statusbar.js', ['plt.wescheme.WeSchemeStatusBar'], ['plt.wescheme.WeSchemeIntentBus']);
goog.addDependency('../../../js-src/openEditor/textcontainer.js', ['plt.wescheme.WeSchemeTextContainer'], ['plt.wescheme.BrowserDetect', 'plt.wescheme.topKeymap']);
goog.addDependency('../../../js-src/openEditor/tokenizer.js', ['plt.wescheme.tokenizer'], []);
goog.addDependency('../../../js-src/openEditor/topkeymap.js', ['plt.wescheme.topKeymap'], ['plt.wescheme.BrowserDetect']);
goog.addDependency('../../../js-src/program.js', ['plt.wescheme.Program'], ['plt.wescheme.SharedAs', 'plt.wescheme.WeSchemeProperties', 'plt.wescheme.base64']);
goog.addDependency('../../../js-src/programdigest.js', ['plt.wescheme.ProgramDigest'], ['plt.wescheme.SharedAs']);
goog.addDependency('../../../js-src/provideModule/provideModule.js', [], ['plt.wescheme.AjaxActions']);
goog.addDependency('../../../js-src/run.js', ['plt.wescheme.runner'], ['plt.compiler.analyze', 'plt.compiler.compile', 'plt.compiler.desugar', 'plt.compiler.lex', 'plt.compiler.parse', 'plt.wescheme.AjaxActions', 'plt.wescheme.RoundRobin', 'plt.wescheme.WeSchemeProperties', 'plt.wescheme.makeDynamicModuleLoader'], {'lang': 'es6'});
goog.addDependency('../../../js-src/sharedas.js', ['plt.wescheme.SharedAs'], []);
goog.addDependency('../../../js-src/sharingdialog.js', ['plt.wescheme.SharingDialog'], ['goog.ui.AdvancedTooltip', 'plt.wescheme.AjaxActions', 'plt.wescheme.WeSchemeIntentBus', 'plt.wescheme.helpers']);
goog.addDependency('../../../js-src/splash.js', [], ['plt.wescheme.browserCheck']);
goog.addDependency('../../../js-src/view.js', [], ['plt.wescheme.AjaxActions', 'plt.wescheme.Program', 'plt.wescheme.helpers']);
goog.addDependency('../../../js-src/wescheme-properties.js', ['plt.wescheme.WeSchemeProperties'], []);

